# Generated by Django 5.2.6 on 2025-09-06 01:33

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "خبر",
                "verbose_name_plural": "خبریں",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="خلاصہ"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مصنف",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_articles",
                to="core.category",
                verbose_name="زمرہ",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="مواد"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تخلیق"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="news_images/", verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[("draft", "ڈرافٹ"), ("published", "شائع شدہ")],
                default="draft",
                max_length=10,
                verbose_name="حالت",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ تازہ کاری"),
        ),
        migrations.AlterField(
            model_name="news",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="ناظرین"),
        ),
    ]
